services:
  traefik:
    container_name: traefik
    image: ${WARDEN_IMAGE_REPOSITORY}/traefik:${TRAEFIK_VERSION:-3.6}
    ports:
      - "${TRAEFIK_LISTEN:-127.0.0.1}:80:80"     # The HTTP port
      - "${TRAEFIK_LISTEN:-127.0.0.1}:443:443"   # The HTTPS port
    volumes:
      - ${WARDEN_HOME_DIR}/etc/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${WARDEN_HOME_DIR}/etc/traefik/providers:/etc/traefik/providers
      - ${WARDEN_HOME_DIR}/ssl/certs:/etc/ssl/certs/warden
      - ${WARDEN_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    labels:
      # Redirect HTTP to HTTPS
      - traefik.http.middlewares.traefik-redirect-https.redirectscheme.scheme=https
      - traefik.http.middlewares.traefik-redirect-https.redirectscheme.permanent=true
      # Main router for traefik dashboard
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${WARDEN_SERVICE_DOMAIN:-warden.test}`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=traefik-redirect-https
      # HTTP router (redirect to HTTPS)
      - traefik.http.routers.traefik-http.rule=Host(`traefik.${WARDEN_SERVICE_DOMAIN:-warden.test}`)
      - traefik.http.routers.traefik-http.entrypoints=http
      - traefik.http.routers.traefik-http.middlewares=traefik-redirect-https
      - traefik.http.routers.traefik-http.service=noop@internal
    restart: ${WARDEN_RESTART_POLICY:-always}

  tunnel:
    container_name: tunnel
    image: panubo/sshd:latest
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - ${WARDEN_HOME_DIR}/tunnel/ssh_key.pub:/etc/authorized_keys/user
      - sshd_keys:/etc/ssh/keys
    environment:
      - |
        MOTD=Welcome to the Warden SSH tunnel container!

        This tunnel container is used only for forwarding TCP
        connections, generally to port 3306 of db containers
        and is not typically used with an interactive shell.

      - SSH_USERS=user:2000:2000
      - TCP_FORWARDING=true
    restart: ${WARDEN_RESTART_POLICY:-always}

  buggregator:
    container_name: buggregator
    image: ghcr.io/buggregator/server:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.buggregator.tls=true
      - traefik.http.routers.buggregator.rule=Host(`buggregator.${WARDEN_SERVICE_DOMAIN:-warden.test}`)
      - traefik.http.routers.buggregator.entrypoints=https
      - traefik.http.services.buggregator.loadbalancer.server.port=8000
      # HTTP router (redirect to HTTPS)
      - traefik.http.routers.buggregator-http.rule=Host(`buggregator.${WARDEN_SERVICE_DOMAIN:-warden.test}`)
      - traefik.http.routers.buggregator-http.entrypoints=http
      - traefik.http.routers.buggregator-http.middlewares=traefik-redirect-https
      - traefik.http.routers.buggregator-http.service=noop@internal
    restart: ${WARDEN_RESTART_POLICY:-always}

volumes:
  portainer:
  sshd_keys:

networks:
  default:
    name: warden
