---
api:
  dashboard: true
providers:
  file:
    directory: /etc/traefik/providers
    watch: true
  docker:
    network: warden
    defaultRule: "Host(`{{ .Name }}.warden.test`)"
    exposedByDefault: false
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
log:
  level: info
global:
  checkNewVersion: false
  sendAnonymousUsage: false
experimental:
  localPlugins:
    csp-merge:
      moduleName: github.com/magenius-team/traefik-csp-merge
